Linenums addition
rdbende/chlorophyll pull request #15
Opened 2023-04-07 18:06 UTC by Moosems

2023-04-07 18:41 UTC, Moosems commented
@rdbende Check here for the PR.

2023-04-09 18:29 UTC, Moosems commented
Fixes #4

2023-04-09 18:38 UTC, rdbende requested changes

2023-04-09 18:38 UTC, rdbende commented on chlorophyll/codeview.py
> +        self.vertical_scroll((yview := self.yview())[0], yview[1])
Walrus is good, but first, I want Chlorophyll to work on Py3.7 till July, and second, it's unnecessary in this case.
```suggestion
        self.horizontal_scroll(*self.xview())
        self.vertical_scroll(*self.yview())
```
Is this method needed at all?

2023-04-09 18:38 UTC, rdbende commented on chlorophyll/codeview.py
> +    ) -> "CodeView":
We don't need the quotes around it. There's a `from __future__ import annotations` statement at the top of the file, so it'll work without the quotes.

2023-04-09 18:38 UTC, rdbende commented on chlorophyll/codeview.py
> +        last: str | float,
```suggestion
        last: str | float
```
Maybe remove the comma, and reformat it with black. It would fit on one line

2023-04-09 18:57 UTC, rdbende commented on requirements.txt
> +tklinenums
Require 1.6.1 at least

2023-04-09 19:13 UTC, rdbende approved these changes

2023-04-09 19:13 UTC, merged