Use auto-hiding scrollbars for codeview
rdbende/chlorophyll pull request #46
Opened 2023-07-20 17:57 UTC by billyeatcookies

## Changes
- Codeview uses auto-hiding scrollbars instead of normal ones

2023-07-20 19:20 UTC, Moosems commented
Honestly I really dislike auto-hiding scrollbars in general and it also complicated some app logic that uses winfo_reqwidth and winfo_reqheight.

2023-07-20 19:23 UTC, Moosems commented
Maybe an option for using auto-hiding scroll bars with it set as False by default? This would also require some documentation and probably doesn't require a whole file.

2023-07-21 13:55 UTC, billyeatcookies commented
@Moosems requested changes are made, please review again!

2023-07-21 14:01 UTC, Moosems requested changes
Few changes/clarification necessary but perfect otherwise!

2023-07-21 14:01 UTC, Moosems commented on chlorophyll/codeview.py
> +        if self.autohide:
Needs to have a grid() in an else for the main if statement.

2023-07-21 14:02 UTC, rdbende commented on chlorophyll/codeview.py
> +        if self.autohide:
Actually, why?

2023-07-21 14:04 UTC, rdbende commented on chlorophyll/codeview.py
> +                self.grid()
Yes. `grid_remove` saves the previous position, and `grid` will restore that.

2023-07-21 14:19 UTC, rdbende approved these changes

2023-07-21 14:21 UTC, Moosems commented on chlorophyll/codeview.py
> +        if self.autohide:
My bad, :).

2023-07-21 14:21 UTC, Moosems approved these changes
Looks good! Great job @billyeatcookies!

2023-07-21 14:21 UTC, Moosems commented
@rdbende You want to merge?

2023-07-21 14:24 UTC, rdbende commented
Whatever :) You have the permission too.

2023-07-21 14:24 UTC, merged