Auto hide the scrollbar by default and Added ` linenum_border`
rdbende/chlorophyll pull request #48
Opened 2024-03-10 05:44 UTC by Sidmaz666

1.  Set Scrollbar Auto hide to True by Default.
2.  Added new param for CodeView, `linenum_border`  to specify the border width of the Line Number Canvas.

2024-03-11 04:54 UTC, whmsft approved these changes
Looks good enough to me... Let the "Benevolent Dictator" @rdbende review it himself

2024-03-11 18:50 UTC, Moosems commented
Woah @whmsft, haven't seen you in a hot minute!

2024-03-11 21:59 UTC, whmsft commented
> Woah @whmsft, haven't seen you in a hot minute!

Great to reconnect dear. I’ve been into tiny game development lately, but my studies have kept me busy... 
Hope you’re well! 😊

2024-03-23 12:25 UTC, rdbende requested changes
I'm not sure you wanted to commit `example.py`, or it's just a mistake, but I'd rather not have an example file in the project root directory.

2024-03-23 12:25 UTC, rdbende commented on chlorophyll/codeview.py
> +        linenum_border = 0,
```suggestion
        linenums_border: int = 0,
```

2024-03-23 12:25 UTC, rdbende commented on chlorophyll/codeview.py
> +            borderwidth=kwargs.get("borderwidth", linenum_border)
```suggestion
            borderwidth=kwargs.get("borderwidth", linenums_border)
```

2024-03-23 12:28 UTC, rdbende commented on README.md
> +|linenum_border    |Line Number Border Width        |Int                                           |
```suggestion
|linenums_border   |Border width of the line numbers|Int                                           |
```

2024-03-23 12:28 UTC, rdbende commented on README.md
> +|linenum_border    |Line Number Border Width        |Int                                           |
Hmm, actually `linenums_theme` is missing from here @Moosems

2024-03-27 15:41 UTC, Moosems commented
Honestly kinda sad I'm getting left out of the reviews when I wrote the linebar lib 🤣

2024-03-27 18:42 UTC, rdbende commented
@Moosems, please review and squash merge it, if it looks good to you :)

2024-03-27 18:45 UTC, Moosems reviewed
The code all checks out by why are we auto hiding the scroll bar by default?

2024-03-27 18:46 UTC, Moosems commented
I just see it causing issues for those who have it in older projects and never used the feature and them being confused why their scroll bar is gone now

2024-03-27 18:47 UTC, rdbende commented on chlorophyll/codeview.py
> +        autohide_scrollbar: bool = True,
Because there's really no reason for having a scrollbar when the view isn't scrollable.

2024-03-27 18:48 UTC, rdbende commented
> I just see it causing issues for those who have it in older projects and never used the feature and them being confused why their scroll bar is gone now

Then I think we can just mark it as a breaking change (even though it isn't) and release it as 0.5

2024-03-27 21:59 UTC, Moosems commented on chlorophyll/codeview.py
> +        autohide_scrollbar: bool = True,
The issue is that it forces resizing which can become a complication

2024-03-27 22:17 UTC, rdbende commented on chlorophyll/codeview.py
> +        autohide_scrollbar: bool = True,
That's something that should be fixed regardless, but making this behaviour default is sensible to me.

2024-03-27 22:18 UTC, rdbende approved these changes

2024-03-27 22:18 UTC, merged