Added context menu feature
rdbende/chlorophyll pull request #49
Opened 2024-03-28 10:04 UTC by whmsft

I thought I should do something, and thought to add simple context menus to the CodeView widget.
(Honestly, what description you want here?)

One screenshot and code snippet is more than enough.
![image](https://github.com/rdbende/chlorophyll/assets/72214351/10581070-f269-4b11-b135-ab027bfa5eff)
```python
import tkinter as tk
import pygments
from chlorophyll import CodeView

root = tk.Tk()
editor = CodeView(root, undo=True,
        font = "Iosevka\ Curly\ Light\ Extended 14",
        lexer=pygments.lexers.PythonLexer, color_scheme="ayu-dark",
        context_menu=True
    )
editor.context_menu.add_separator()
editor.context_menu.add_command(label="A custom command", command=lambda:print("lame"))

editor.pack(expand=True, fill='both')
root.mainloop()
```

2024-03-28 10:06 UTC, whmsft commented
Also, @Moosems I and @rdbende were thinking about whether we should set `undo=True` (since it's like the bare minimum for Text widgets) or leave it to `False` for Tkinter's "90's compatibility". What are your opinions?

2024-03-28 10:07 UTC, Moosems commented
It's almost always turned on anyway so yeah, that seems good

2024-03-29 04:09 UTC, whmsft commented
@Moosems thanks for your input...
I'd be glad if you take a deep look at my PR and point out any mistakes

2024-03-29 11:39 UTC, Moosems approved these changes
Looks great to me!

2024-03-29 12:16 UTC, rdbende commented
In my opinion, it would be better to have a read-only property, that abstracts the `_context_menu` field, and lazy-initializes the menu instance (i.e. only, when needed/the property is accessed). The `context_menu` option could be renamed to `default_context_menu`, so that you can also get an empty menu, but there's an option to fill it with the default items.

2024-03-29 17:19 UTC, rdbende requested changes
Thanks! This looks really good. Now the only thing I'm wondering about is whether `default_context_menu` should be `True` by default.
Thoughts? @Moosems ?

2024-03-29 17:19 UTC, rdbende commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
Nit:
```suggestion
            super().bind("<Button-3>", lambda e: self._context_menu.tk_popup(e.x_root, e.y_root))
```

Also, this doesn't work on macOS, as it doesn't have Button-3, it needs to be something like `Control-Button-1`, but I don't know from the top of my head.

2024-03-29 17:19 UTC, rdbende commented on chlorophyll/codeview.py
> +
```suggestion
```

You didn't quite follow the emperor's order. You'll get executed 😂

I think this property should be read-only, because it's not necessary to be able to set an entirely custom menu object, and could lead to unnecessary headaches, when one sets an incorrect parent, or forgets to bind the menu to right-click.

2024-03-29 17:19 UTC, rdbende commented on chlorophyll/codeview.py
> +            context_menu.add_command(label="Cut", command=lambda:self.event_generate("<<Cut>>"))
```suggestion
            context_menu.add_command(label="Undo", command=lambda: self.event_generate("<<Undo>>"))
            context_menu.add_command(label="Redo", command=lambda: self.event_generate("<<Redo>>"))
            context_menu.add_separator()
            context_menu.add_command(label="Cut", command=lambda: self.event_generate("<<Cut>>"))
```

2024-03-29 18:15 UTC, Moosems commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
I was wondering that myself but thought it did lol

2024-03-29 18:16 UTC, Moosems commented
Honestly it *is* the ___`default`___`_context_menu` so I don't know, you make the call

2024-03-29 18:46 UTC, whmsft commented on chlorophyll/codeview.py
> +            context_menu.add_command(label="Cut", command=lambda:self.event_generate("<<Cut>>"))
Not sure which code style you follow, but I'll resolve it.

2024-03-29 18:47 UTC, Moosems commented on chlorophyll/codeview.py
> +
![kuzco-emeperors-new-groove](https://github.com/rdbende/chlorophyll/assets/95927277/644cad9c-c1c9-4f82-9ed7-ac41052e2bce)

2024-03-29 18:56 UTC, whmsft commented on chlorophyll/codeview.py
> +
Looks like I'm about to get guillotined for high treason.

2024-03-29 18:57 UTC, Moosems commented on chlorophyll/codeview.py
> +
No, more likely the brazen bull.

2024-03-29 19:02 UTC, rdbende commented on chlorophyll/codeview.py
> +            context_menu.add_command(label="Cut", command=lambda:self.event_generate("<<Cut>>"))
It's black

2024-03-29 19:03 UTC, rdbende commented on chlorophyll/codeview.py
> +            context_menu.add_command(label="Cut", command=lambda:self.event_generate("<<Cut>>"))
I use Black for every of my projects locally, dunno why I don't have a GH Action on this repo yet.

2024-03-29 19:05 UTC, whmsft commented on chlorophyll/codeview.py
> +
The moment I realize I'm due for the worst punishment
![Screenshot_2024-03-30-00-34-01-547_ai.perplexity.app.android.jpg](https://github.com/rdbende/chlorophyll/assets/72214351/35cf39a5-2dc1-4bb5-9b23-2f21627ef6e8)

2024-03-29 19:14 UTC, whmsft commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
What are we to do of Button-3?
I now read somewhere "1=left click, 2=right click & 3=middle click" in tkinter. And AI is also vomiting some unreasonable shit. Maybe need to read "official docs"

2024-03-29 19:24 UTC, rdbende commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
For me it's always just faster tu pull up TkDocs: https://tkdocs.com/tutorial/menus.html

2024-03-29 19:48 UTC, whmsft commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
Reading the docs, I believe we're accepting this?
```python
if tk.Tk().tk.call("tk", "windowingsystem") == "aqua":
    super().bind("<Control-Button-1>", lambda e: self._context_menu.tk_popup(e.x_root + 10, e.y_root + 10))
else:
    super().bind("<Button-3>", lambda e: self._context_menu.tk_popup(e.x_root + 10, e.y_root + 10)) 
```
Confirm, then I'll commit the final thing myself.

2024-03-29 19:50 UTC, rdbende commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
I already committed :)

2024-03-29 19:53 UTC, whmsft commented on chlorophyll/codeview.py
> +            super().bind("<Button-3>", lambda e:self._context_menu.tk_popup(e.x_root, e.y_root))
That's great... (I think GitHub Mobile should notify if such a thing occurs)
So now we can say it's resolved?

2024-03-29 21:14 UTC, Moosems commented on chlorophyll/codeview.py
> +
.1 Kb/S is quite the slow data speed 😄

2024-03-29 21:17 UTC, rdbende commented on chlorophyll/codeview.py
> +
Mine isn't faster either at idle

![image](https://github.com/rdbende/chlorophyll/assets/77941087/0e4e5a22-54d0-4282-9619-1809baab64cd)

2024-03-29 21:29 UTC, Moosems commented on chlorophyll/codeview.py
> +
@rdbende Could you go on Discord for a minute, I need some Linux help

2024-03-30 00:03 UTC, whmsft commented on chlorophyll/codeview.py
> +
> .1 Kb/S is quite the slow data speed 😄

If I do any intensive task it can jump up to 1 Mb/s in a sec... When you do nothing what speed you expect? 😂

2024-03-30 00:14 UTC, whmsft commented on chlorophyll/codeview.py
> +
> @rdbende Could you go on Discord for a minute, I need some Linux help

Did you mean you both are also in discord? I definitely want your usernames...

2024-03-30 06:07 UTC, whmsft commented
@rdbende, it seems that your commit with `if super().tk.call("tk", "windowingsystem") == "aqua":` doesn't work for me:
```
$ python3 example.py
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    codeview_01.context_menu.add_separator()
  File "E:\Programming\_github\chlorophyll\chlorophyll\codeview.py", line 108, in context_menu
    if super().tk.call("tk", "windowingsystem") == "aqua":
AttributeError: 'super' object has no attribute 'tk'
```
I changed `super().*` to `self.*` and it works like a charm.

2024-03-30 06:28 UTC, whmsft commented
Moreover, I also realized that if you create a CodeView with `default_context_menu=True`, you ought to be expecting the context menu to be created, and not call `CodeView.context_menu.xx()` to initialize the object. Does anyone agree with me?
That being said, shouldn't we have `if self._default_context_menu: self.context_menu` to initialize the instance right after `self._default_context_menu = default_context_menu`?

2024-03-30 09:08 UTC, rdbende commented
> That being said, shouldn't we have if self._default_context_menu: self.context_menu to initialize the instance right after self._default_context_menu = default_context_menu?

Oh, yeah that's missing

2024-03-30 09:58 UTC, whmsft commented
Now, check for any mistakes... 🤞

2024-03-30 14:07 UTC, rdbende approved these changes

2024-03-30 14:09 UTC, rdbende commented
Unrelated, but I still don't like pyperclip

It now says, that it can't find a clipboard implementation for my system (probably because it was running inside a distrobox with nothing but base Debian and tkinter installed)

```yaml
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/run/host/tmp/chlorophyll/chlorophyll/codeview.py", line 163, in _copy
    copy(text)
  File "/run/host/tmp/chlorophyll/env/lib/python3.11/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
           ^^^^^^^^^^
  File "/run/host/tmp/chlorophyll/env/lib/python3.11/site-packages/pyperclip/__init__.py", line 336, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
```

2024-03-30 14:10 UTC, rdbende approved these changes

2024-03-30 14:11 UTC, merged